Repository Monitoring-Mtl/Frontend, pull requests merged in 2023-11, with the labels that each got.

#24 Features/layout
  README.md
  package-lock.json
  package.json
  public/logo-pfe.png
  src/app/components/Button.tsx
  src/app/components/TxtDanger.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/layouts/BasicFormLayout.tsx
  src/app/layouts/SelectBusLineForm.tsx
Labels: fonctionnalité

#26 Ajout du graphique d'accès aux rampes
  src/app/page.tsx
  src/components/AccessRampGraph.tsx
Labels: fonctionnalité

#28 Quelques améliorations générales du style de la page
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/AccessRampGraph.tsx
  src/models/MapProxy.ts
Labels: UI/UX

#30 Réusinage de la carte pour qu'elle soit un composant
  src/app/page.tsx
  src/components/map/Map.tsx
  src/components/map/StmMap.tsx
  src/models/MapProxy.ts
  src/types/mapTypes.ts
Labels: réusinage

#37 Simplification du système de factories et ajout des données sur les routes
  src/app/page.tsx
  src/components/map/StmMap.tsx
  src/factories/StmFactory.ts
  src/factories/factoryInterfaces.ts
  src/factories/mocks/MockStmFactory.ts
  src/factories/mocks/mockData.ts
  src/factories/propertyObjects.ts
  src/services/ServerlessApiService.ts
  src/types/stmTypes.ts
Labels: fonctionnalité, réusinage

#39 fix UI
  package-lock.json
  src/app/components/BusLineOptionList.tsx
  src/app/components/Button.tsx
  src/app/components/FullButton.tsx
  src/app/components/PieChart.tsx
  src/app/components/StopIdOptionList.tsx
  src/app/components/TxtDanger.tsx
  src/app/components/dummyTest.js
  src/app/components/map/Map.tsx
  src/app/components/map/StmMap.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/layouts/BasicFormLayout.tsx
  src/app/layouts/Footer.tsx
  src/app/layouts/Header.tsx
  src/app/layouts/Legend.tsx
  src/app/layouts/PieChart.tsx
  src/app/layouts/Row.tsx
  src/app/layouts/SelectBusLineForm.tsx
  src/app/page.tsx
  src/components/AccessRampGraph.tsx
  src/components/Button.tsx
  src/components/map/StmMap.tsx
  tailwind.config.ts
  tests/components/dummy.test.js
  yarn.lock
Labels: fonctionnalité

#40 Fix warnings (document undefined, mui select)
  src/app/components/PieChart.tsx
  src/app/layouts/PieChart.tsx
  src/app/layouts/SelectBusLineForm.tsx
Labels: bug

#43 Ajout du graphique pour le taux d'occupation
  package-lock.json
  package.json
  src/app/components/graphs/BarChart.tsx
  src/app/components/graphs/OccupancyChart.tsx
  src/app/components/graphs/PieChart.tsx
  src/app/components/map/StmMap.tsx
  src/app/layouts/BarChart.tsx
  src/app/layouts/PieChart.tsx
  src/app/page.tsx
  src/types/BarChartOptions.ts
  src/types/MapOptions.ts
  src/types/stmTypes.ts
  src/utils/color-utils.ts
Labels: fonctionnalité, UI/UX

#51 Release #3
  .github/workflows/ci.yml
  .gitignore
  README.md
  jest.config.js
  package-lock.json
  package.json
  public/logo-pfe.png
  src/app/components/BusLineOptionList.tsx
  src/app/components/Button.tsx
  src/app/components/FullButton.tsx
  src/app/components/StopIdOptionList.tsx
  src/app/components/TxtDanger.tsx
  src/app/components/dummyTest.js
  src/app/components/graphs/BarChart.tsx
  src/app/components/graphs/OccupancyChart.tsx
  src/app/components/graphs/PieChart.tsx
  src/app/components/map/Map.tsx
  src/app/components/map/StmMap.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/layouts/BarChart.tsx
  src/app/layouts/Footer.tsx
  src/app/layouts/Header.tsx
  src/app/layouts/Legend.tsx
  src/app/layouts/PieChart.tsx
  src/app/layouts/Row.tsx
  src/app/layouts/SelectBusLineForm.tsx
  src/app/page.tsx
  src/components/tests/dummy.test.js
  src/factories/StmFactory.ts
  src/factories/propertyObjects.ts
  src/services/ServerlessApiService.ts
  src/services/api/SampleShape.ts
  src/services/api/ServerlessApiService.ts
  src/types/BarChartOptions.ts
  src/types/MapOptions.ts
  src/types/map/MapProxy.ts
  src/types/map/RouteShape.ts
  src/types/stmTypes.ts
  src/utils/color-utils.ts
  tailwind.config.ts
  tests/components/dummy.test.js
  to_copy_under_.git_hooks/pre-commit
  to_copy_under_.git_hooks/pre-commit.bat
  to_copy_under_.git_hooks/pre-commit.ps1
Labels: release

#53 Ajout du cadre de tests - unitaires, composants, E2E
  .github/workflows/ci.yml
  .gitignore
  cypress.config.ts
  cypress/e2e/spec.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/component-index.html
  cypress/support/component.ts
  cypress/support/e2e.ts
  cypress/unit/factories.cy.ts
  jest.config.js
  package-lock.json
  package.json
  scripts/ci_tests.sh
  src/app/components/dummyTest.js
  src/app/components/graphs/OccupancyChart.tsx
  src/factories/StmFactory.ts
  tests/components/dummy.test.js
  tsconfig.json
Labels: test

#54 Première version du graphique de ponctualité
  package.json
  src/app/components/graphs/BusPunctualityChart.tsx
  src/app/components/graphs/OccupancyChart.tsx
  src/app/components/graphs/templates/BarChart.tsx
  src/app/components/graphs/templates/PieChart.tsx
  src/app/components/graphs/templates/ScatterPlot.tsx
  src/app/layouts/BarChart.tsx
  src/app/layouts/PieChart.tsx
  src/app/page.tsx
  src/types/ChartjsOptions.ts
  src/utils/color-utils.ts
  src/utils/math-utils.ts
Labels: fonctionnalité

#55 Ajout de tests unitaires et E2E
  cypress/e2e/spec.cy.ts
  cypress/unit/math-utils.cy.ts
  src/app/components/graphs/BusPunctualityChart.tsx
  src/app/components/graphs/OccupancyChart.tsx
  src/utils/math-utils.ts
Labels: test

#58 Ajout du nom des arrêts en overlay sur la carte + un peu de refactor
  src/app/components/map/Map.tsx
  src/app/components/map/StmMap.tsx
  src/types/MapOptions.ts
Labels: fonctionnalité, réusinage

#59 Quelques améliorations mineures au graphique sur la ponctualité
  src/app/components/graphs/BusPunctualityChart.tsx
  src/app/components/graphs/OccupancyChart.tsx
  src/app/components/graphs/templates/BarChart.tsx
  src/app/components/graphs/templates/ScatterPlot.tsx
  src/types/ChartjsOptions.ts
Labels: fonctionnalité

#67 css proposition pierre
  src/app/components/graphs/BusPunctualityChart.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/layouts/Footer.tsx
  src/app/layouts/Legend.tsx
  src/app/page.tsx
Labels: réusinage, UI/UX

#68 Mise à jour du service pour avoir les données des routes
  cypress/unit/factories.cy.ts
  src/app/components/graphs/BusPunctualityChart.tsx
  src/app/components/map/StmMap.tsx
  src/app/page.tsx
  src/factories/StmFactory.ts
  src/factories/propertyObjects.ts
  src/services/ServerlessApiService.ts
  src/types/Direction.ts
  src/types/Route.ts
  src/types/RouteShape.ts
  src/types/Stop.ts
  src/types/stmTypes.ts
Labels: fonctionnalité, réusinage
