Repository Monitoring-Mtl/Frontend, pull requests merged in 2023-10, with the labels that each got.

#4 Création de l'application next.js de base avec carte interactive de base
  .eslintrc.json
  README.md
  next.config.js
  package-lock.json
  package.json
  postcss.config.js
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
  tsconfig.json
Labels: enhancement

#13 Feature/12 automatiser tests unitaires
  .github/workflows/ci.yml
  jest.config.js
  package.json
  src/components/dummyTest.js
  src/components/tests/dummy.test.js
  to_copy_under_.git_hooks/pre-commit
  to_copy_under_.git_hooks/pre-commit.bat
  to_copy_under_.git_hooks/pre-commit.ps1
Labels: CI/CD

#15 Réusinage de la page de la carte, correction d'un petit bug et changement du marqueur pour une route statique
  src/app/page.tsx
  src/services/api/SampleShape.ts
  src/services/api/ServerlessApiService.ts
  src/types/map/MapProxy.ts
  src/types/map/RouteShape.ts
  tsconfig.json
Labels: bug, fonctionnalité, réusinage

#10 pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: CI/CD

#16 Release pour l'itération 2
  .github/workflows/ci.yml
  jest.config.js
  package.json
  src/app/page.tsx
  src/components/dummyTest.js
  src/components/tests/dummy.test.js
  src/services/api/SampleShape.ts
  src/services/api/ServerlessApiService.ts
  src/types/map/MapProxy.ts
  src/types/map/RouteShape.ts
  to_copy_under_.git_hooks/pre-commit
  to_copy_under_.git_hooks/pre-commit.bat
  to_copy_under_.git_hooks/pre-commit.ps1
  tsconfig.json
Labels: release

#18 Réusinage et ajout d'une infrastructure pour pouvoir mock les données
  package-lock.json
  package.json
  src/app/page.tsx
  src/factories/factoryInterfaces.ts
  src/factories/mocks/MockStmFactory.ts
  src/factories/mocks/mockData.ts
  src/factories/propertyObjects.ts
  src/models/MapProxy.ts
  src/services/ServerlessApiService.ts
  src/services/api/ServerlessApiService.ts
  src/types/map/RouteShape.ts
  src/types/mapTypes.ts
Labels: fonctionnalité, réusinage
