Repository Monitoring-Mtl/Frontend, pull requests merged in 2023-12, with the labels that each got.

#71 Intégration du endpoint analyze et ajustement des graphiques
  .github/workflows/ci.yml
  cypress/e2e/spec.cy.ts
  cypress/fixtures/analysis.json
  cypress/fixtures/example.json
  cypress/fixtures/shape.json
  cypress/unit/factories.cy.ts
  cypress/unit/math-utils.cy.ts
  src/app/components/graphs/AccessRampChart.tsx
  src/app/components/graphs/BusPunctualityChart.tsx
  src/app/components/graphs/OccupancyChart.tsx
  src/app/components/graphs/templates/PieChart.tsx
  src/app/layouts/PieChart.tsx
  src/app/page.tsx
  src/factories/StmFactory.ts
  src/services/ServerlessApiService.ts
  src/types/Arc.ts
  src/types/ChartjsOptions.ts
  src/types/StmAnalysis.ts
  src/types/stmTypes.ts
Labels: fonctionnalité, réusinage

#52 Menu déroulant de la ligne d'autobus + sélecteur direction+ arrêt + date hour minute picker + console.log le formulaire à la soumission
  src/app/layout.tsx
  src/app/layouts/ControlsForm.tsx
  src/app/layouts/SelectBusLineForm.tsx
  src/app/page.tsx
  src/css/globals.css
Labels: fonctionnalité

#76 Intégration du form et des visualisations
  .github/pull_request_template.md
  cypress/unit/datetime-utils.cy.ts
  cypress/unit/factories.cy.ts
  package-lock.json
  package.json
  src/app/components/map/StmMap.tsx
  src/app/layouts/ControlsForm.tsx
  src/app/page.tsx
  src/factories/StmFactory.ts
  src/services/ServerlessApiService.ts
  src/types/stmTypes.ts
  src/utils/datetime-utils.ts
Labels: fonctionnalité

#78 Release #4 (v0.4.0)
  .github/pull_request_template.md
  .github/workflows/ci.yml
  .gitignore
  cypress.config.ts
  cypress/e2e/spec.cy.ts
  cypress/fixtures/analysis.json
  cypress/fixtures/shape.json
  cypress/support/commands.ts
  cypress/support/component-index.html
  cypress/support/component.ts
  cypress/support/e2e.ts
  cypress/unit/datetime-utils.cy.ts
  cypress/unit/factories.cy.ts
  cypress/unit/math-utils.cy.ts
  jest.config.js
  package-lock.json
  package.json
  scripts/ci_tests.sh
  src/app/components/dummyTest.js
  src/app/components/graphs/AccessRampChart.tsx
  src/app/components/graphs/BusPunctualityChart.tsx
  src/app/components/graphs/OccupancyChart.tsx
  src/app/components/graphs/PieChart.tsx
  src/app/components/graphs/templates/BarChart.tsx
  src/app/components/graphs/templates/PieChart.tsx
  src/app/components/graphs/templates/ScatterPlot.tsx
  src/app/components/map/Map.tsx
  src/app/components/map/StmMap.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/layouts/BarChart.tsx
  src/app/layouts/ControlsForm.tsx
  src/app/layouts/Footer.tsx
  src/app/layouts/Legend.tsx
  src/app/layouts/PieChart.tsx
  src/app/layouts/SelectBusLineForm.tsx
  src/app/page.tsx
  src/css/globals.css
  src/factories/StmFactory.ts
  src/factories/propertyObjects.ts
  src/services/ServerlessApiService.ts
  src/types/Arc.ts
  src/types/BarChartOptions.ts
  src/types/ChartjsOptions.ts
  src/types/Direction.ts
  src/types/MapOptions.ts
  src/types/Route.ts
  src/types/RouteShape.ts
  src/types/StmAnalysis.ts
  src/types/Stop.ts
  src/types/stmTypes.ts
  src/utils/color-utils.ts
  src/utils/datetime-utils.ts
  src/utils/math-utils.ts
  tests/components/dummy.test.js
  tsconfig.json
Labels: release

#80 Features/spinner
  src/app/layouts/ControlsForm.tsx
  src/app/page.tsx
Labels: fonctionnalité

#88 Quelques améliorations visuelles pour la carte
  src/app/components/map/StmMap.tsx
  src/utils/color-utils.ts
Labels: UI/UX

#90 Validation date-heure-minute debut-fin
  src/app/layouts/ControlsForm.tsx
Labels: fonctionnalité

#92 Grossir la largeur des contrôles
  src/app/page.tsx
Labels: UI/UX

#94 L'arrêt sélectionné à une couleur différente
  src/app/components/map/StmMap.tsx
  src/app/layouts/ControlsForm.tsx
  src/app/page.tsx
Labels: UI/UX

#95 Good case of e2e ControlsFormTest
  cypress/e2e/ControlsFormTest.cy.ts
  src/app/layouts/ControlsForm.tsx
Labels: test

#96 2 Cas de tests fautifs concernant les date-heure-minute
  cypress/e2e/ControlsFormTest.cy.ts
  src/app/layouts/ControlsForm.tsx
Labels: test

#97 Cliquer sur un arrêt change l'arrêt sélectionné
  src/app/components/BusLineOptionList.tsx
  src/app/components/Button.tsx
  src/app/components/StopIdOptionList.tsx
  src/app/components/TxtDanger.tsx
  src/app/components/map/Map.tsx
  src/app/components/map/StmMap.tsx
  src/app/layouts/ControlsForm.tsx
  src/app/page.tsx
  src/types/MapOptions.ts
Labels: fonctionnalité

#98 Validation date heure minute
  cypress/e2e/ControlsFormTest.cy.ts
  src/app/layouts/ControlsForm.tsx
Labels: bug

#91 disable button when form is not complete
  src/app/components/FullButton.tsx
  src/app/layouts/ControlsForm.tsx
Labels: UI/UX

#99 Ajout de toasts pour les messages d'erreur et vérification des données d'analyse
  cypress/e2e/ControlsFormTest.cy.ts
  package-lock.json
  package.json
  src/app/layouts/ControlsForm.tsx
  src/app/page.tsx
  src/factories/StmFactory.ts
Labels: UI/UX

#100 Documentation wiki de nvm
  README.md
Labels: documentation

#102 Release v0.4.1
  README.md
  cypress/e2e/ControlsFormTest.cy.ts
  cypress/e2e/spec.cy.ts
  package-lock.json
  package.json
  src/app/components/BusLineOptionList.tsx
  src/app/components/Button.tsx
  src/app/components/FullButton.tsx
  src/app/components/StopIdOptionList.tsx
  src/app/components/TxtDanger.tsx
  src/app/components/graphs/AccessRampChart.tsx
  src/app/components/graphs/BusPunctualityChart.tsx
  src/app/components/graphs/OccupancyChart.tsx
  src/app/components/graphs/templates/BarChart.tsx
  src/app/components/graphs/templates/PieChart.tsx
  src/app/components/map/Map.tsx
  src/app/components/map/StmMap.tsx
  src/app/layouts/ControlsForm.tsx
  src/app/page.tsx
  src/factories/StmFactory.ts
  src/types/MapOptions.ts
  src/utils/color-utils.ts
Labels: release

#105 Mise à jour du README + diagrammes de conception
  README.md
  design/renders/access-design.png
  design/renders/frontend-design.png
  design/renders/map-design.png
  design/renders/occupancy-design.png
  design/renders/pattern-design.png
  design/renders/punctuality-design.png
  design/v4/access_design.puml
  design/v4/frontend_design.puml
  design/v4/map_design.puml
  design/v4/occupancy_design.puml
  design/v4/pattern.puml
  design/v4/punctuality_design.puml
  package.json
Labels: documentation

#106 Dernier release de la version 4
  README.md
  design/renders/access-design.png
  design/renders/frontend-design.png
  design/renders/map-design.png
  design/renders/occupancy-design.png
  design/renders/pattern-design.png
  design/renders/punctuality-design.png
  design/v4/access_design.puml
  design/v4/frontend_design.puml
  design/v4/map_design.puml
  design/v4/occupancy_design.puml
  design/v4/pattern.puml
  design/v4/punctuality_design.puml
  package.json
Labels: release
